### ISSUE TITLE
Self closing tag with spaces.

### ISSUE THREAD

**Issue by smith288** [uacaps/NSObject-ObjectMap#1]
I have a node called &lt;StatusMessage /&gt; but it seems to cause issues with the rest of the properties not being filled out. 

I think it's the space between StatusMessage and the />

**Comment by MatthewYork** [comment]
Sorry for the problem. We will take a look at this first thing on Monday morning.

**Comment by smith288** [comment]
Any closer?  I'd love to ditch the google library for yours.

**Comment by bennyguitar** [comment]
We put a test Xcode demo project up called **MappingTest** that tries to recreate your problem, but we couldn't get the same behavior. See if you can replicate the issue in a fresh project with nothing but the ObjectMapper class in it.

A question comes to mind for me:
- Is your XML valid? There are XML linting websites that will check for validity online.

If you want us to kind of pore over exactly what you're doing, you can send some code snippets to bgordon [at] cs.ua.edu and we'll look at them and try to replicate the problem on our end.

Thanks for raising the issue - I'm going to leave it open for now.

**Comment by smith288** [comment]
The XML comes in as SOAP from a MS web service so i'm pretty sure the format is correct.  I'll try what you said and see if I can duplicate it there as well.  Thanks...

**Comment by MatthewYork** [comment]
Just out of curiosity, are those other properties that are not being parsed primitives? We don't currently support those, so it would make sense if they didn't get parsed correctly. If so, try making those properties NSNumbers, and everything should work.

**Comment by smith288** [comment]
All NSStrings.

**Comment by bennyguitar** [comment]
The newest commit eebf223 should fix everything for you. Thanks for being patient through the process.
