### ISSUE TITLE
Double Alloc

### ISSUE THREAD

**Issue by bennyguitar** [uacaps/NSObject-ObjectMap#10]
In our main methods (<code>initWithData:type:</code> and their JSON/XML/SOAP equivalents), we're basically double alloc-ing, and I'm not sure if this has any negative effects. Does ARC take care of this? I know it can't be great practice, and we're working on refactoring things to make JSON/XML/SOAP -> Objects make the most sense from a semantic/conceptual standpoint.

Does anyone have thoughts on this?

**Comment by vittoriom** [comment]
Have you considered skipping the <code>objectOfClass:</code> and derivatives call? 
What's the barrier in implementing directly the initialization in the <code>initWithData:</code> and derivatives?
