### ISSUE TITLE
Error while running the demo project MapTest

### ISSUE THREAD

**Issue by ligilmoneylal** [uacaps/NSObject-ObjectMap#11]
showing "EXC_BAD_ACCESS" error while running the sample code

This is an infinite loop error due to the failure of finding the corresponding end tags of xml data
![screen shot 2014-01-06 at 11 58 24 am](https://f.cloud.github.com/assets/5699156/1848837/fd455aac-769b-11e3-92e8-2e71c8e12af2.png)

**Comment by MatthewYork** [comment]
Fixed. Thanks for finding this. We broke a few things and needed to revert.

Regards,

-Matt
