### ISSUE TITLE
JSON-Boolean <---> Objective-C BOOL

### ISSUE THREAD

**Issue by Andrej1A** [uacaps/NSObject-ObjectMap#13]
I use a JSON API with boolean properties. 
For example: 
{
     "is_used": false, 
     "is_unique": true 
} 

This allows your class to deal only during deserialization, but not in the serialization. What would be a good way to solve this?

**Comment by MatthewYork** [comment]
So your API will not support 0/1 as boolean coming back to it? Just curious.

**Comment by Andrej1A** [comment]
0 and false are not the same. Some libraries accept the 0 as false, but the JSON specification says that 0 is a number. My API doesn't support it.
