### ISSUE TITLE
Subclassing - Init infinite loop

### ISSUE THREAD

**Issue by pr8x** [uacaps/NSObject-ObjectMap#14]
How does subclassing work using the `initWithJSONData` constructor?
Given the following class constructor (invoked only once):

```

- (id)init {
    NSData* raw = [NSData dataWithContentsOfFile:
                   [[NSBundle mainBundle] pathForResource:@"user" ofType:@"json"]];
    if (self = [MCUser initWithJSONData:raw]) {

    }
    return self;
}

```

Replacing `MCUser initWith..` with `self` or `super` also brings the same result.

The app enters an **infinite loop** (EXC_BAD_ACCESS).
Any idea how use it properly?

**Comment by MatthewYork** [comment]
I think you are calling a class's init method from itself, causing an infinite loop.

NSObject+ObjectMap reads properties from parent classes until it reaches the base class (NSObject). So, in essence, you get it for free without having to think about mapping them.

Now, as for actually mapping a class, you don't do it inside of the classes init function. Instead, you would do this from a controller or other place like so.  

``` smalltalk
MCUser *user = [[MCUser alloc] initWithJSONData:data];
```

If MCUser inherits from another class (say, MCBaseUser), then it will map any of MCBaseUser's properties from JSON as well.

Hope this helps.

-Matt

**Comment by pr8x** [comment]
I am using a singletone class that is meant to be populated by the `init` procedure. Is there any way to load json data into an existing object without having to initialize it again?

Like: `[obj loadJson]`

**Comment by MatthewYork** [comment]
Unfortunately, there is no way to do that. Instead of the singleton being populated by a direct mapping of an object, you might try making the desired object a property on the singleton and then calling initWithJSONData for that property.
