### ISSUE TITLE
Complex JSon not able to convert to class object

### ISSUE THREAD

**Issue by ankur-gandhi** [uacaps/NSObject-ObjectMap#17]
Hi,
I have complex Json data. And when I am trying to convert to custom class it is returning nil.
Below is the example of JSon data.
{
"FiltersCount":{
"isFemale":[
{"Id":"T","Count":1310},
{"Id":"F","Count":146},
{"Id":"all_count","Count":1456}]
}
}

I am using Swift and trying to convert to below class's object.
========START=========
import Foundation
class ResultFilterCount : NSObject{
    var FiltersCount : FiltersKeyValue?
    override init(){
        super.init()
        if(self != nil){
            self.setValue("FiltersKeyValue", forKeyPath: "propertyArrayMap.FiltersCount")
        }
    }
}

class FiltersKeyValue: NSObject{
    var isFemale: [FilterResultModel]?
    override init(){
        super.init()
        self.setValue("FilterResultModel", forKeyPath: "propertyArrayMap.isFemale")
    }
}

class FilterResultModel: NSObject{
    var Id : NSString?
    var Count: NSNumber?
    override init(){
        super.init()
        self.setValue("NSString", forKeyPath: "propertyArrayMap.Id")
        self.setValue("NSNumber", forKeyPath: "propertyArrayMap.Count")
    }
}

========END=========

This is the code to convert to class.
var data = results as NSData
var pList = ResultFilterCount(JSONData: data)

Result: It returns nil.
Expected Result : It should return ResultFilterCount object with different properties and values.

thanks
ankur

**Comment by MatthewYork** [comment]
One thing I see is that the line 

``` swift
self.setValue("NSString", forKeyPath: "propertyArrayMap.Id")
```

may not be necessary. Setting the propertyArrayMap key path only needs to happen when the data type is an array. This is because the parser will otherwise not know what object it should be trying to parse since it is not explicitly given in the JSON.

Also, I haven't done any testing in Swift, so your guess is as good as mine here.
