### ISSUE TITLE
How to fetch Soap String 

### ISSUE THREAD

**Issue by nishsheth** [uacaps/NSObject-ObjectMap#18]
I have used [[Class alloc]initWithSOAPData:operation.responseData]; . When I tried to fetch Soap String app crashed with this error '-[Class Header]: unrecognized selector sent to instance .

**Comment by mythodeia** [comment]
@nishith18 
how did you try to get the SOAPString? I am using it with JSON and do not have any issues when getting the JSONString. 
The error message you get means that it cannot find the specific method you are trying to use.

**Comment by nishsheth** [comment]
I am using for  XML .I am trying with this way classObject.SOAPString .

**Comment by mythodeia** [comment]
@nishith18 
i am calling it `[self JSONString]` from within the object.
if you hold the command button and click on the SOAPString word in your class in XCode does it take you to the SOAPString method of the NSObject+ObjectMap category? 

```
// example usage:
CustomObject *customObj = [[CustomObject alloc] initWithSOAPData:operation.responseData];
NSLog(@"%@",[customObj SOAPString]);
```

**Comment by nishsheth** [comment]
Yes It does . 
I have used same way you have described above .

**Comment by mythodeia** [comment]
@nishith18 
did you check the operation.responseData if the returned value is valid? have you made all necessary imports to your header?

**Comment by qq562641869** [comment]
It don't support soap string..
