### ISSUE TITLE
null node get value error

### ISSUE THREAD

**Issue by xiaoyangh** [uacaps/NSObject-ObjectMap#7]
hi: i found a bug
such as this xml:<CITYCODE>PEK</CITYCODE>
        <CONTINENTCN/>
        <CONTINENTEN/>
        <COUNTRYCNNAME>AM</COUNTRYCNNAME>
    </CITY>
at last the CONTINENTCN node value is[<CONTINENTEN/><COUNTRYCNNAME>AM] how can solve? 

![2013-11-14 11 04 08](https://f.cloud.github.com/assets/1456254/1538104/fd07b1d4-4cd9-11e3-9b77-6e2fbb170aaa.png)

**Comment by MatthewYork** [comment]
I'm sorry, but I don't understand the problem. Please post a sample of the XML in question and we will attempt to recreate the problem.

**Comment by xiaoyangh** [comment]
hi the xml is 
![2013-11-14 11 19 06](https://f.cloud.github.com/assets/1456254/1538149/91595990-4cdb-11e3-8e63-d242a33b7cbe.png)

**Comment by xiaoyangh** [comment]
hi MatthewYork ,i found when the xml have a null node ,such this image:
![2013-11-14 11 19 06](https://f.cloud.github.com/assets/1456254/1538155/f0f4d064-4cdb-11e3-8116-c754bfd8ccae.png)

**Comment by MatthewYork** [comment]
To make this work, you need to create another object (perhaps named CITYLIST), and make an NSArray property called CITIES. Map to the CITYLIST object and it should work. This is our workaround for now. We may extend a formal method for XML top-level arrays soon.

**Comment by MatthewYork** [comment]
I'm going to close this issue as we have found a (temporary) solution with the current code. Feel free to open this back up if there is a problem.
